#!/usr/bin/env python3

from glob import glob
import re
import os
import shutil

SOURCE_DIRECTORY = 'art/20210611/02_BUTTONS'
DEST_DIRECTORY = 'assets/buttons'
RELEASE = '0.1'


HEADER = '''/*
 * Copyright (C) 2012-2020  Online-Go.com
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */


/* This file has been automatically generated by preprocess_buttons.py */


'''


stupid_map = {
    "11": "check-light",
    "13": "check-dark",
    "15": "check-light-green",
    "17": "check-dark-green",
    "12": "x-light",
    "14": "x-dark",
    "16": "x-light-green",
    "18": "x-dark-green",

    "19": "flag-light-green",
    "20": "flag-light",
    "21": "flag-dark",
    "22": "flag-dark-green",

    "23": "chat-dark-green",
    "24": "chat-dark",
    "25": "chat-light",
    "26": "chat-light-green",

    "27": "return-light-green",
    "28": "return-light",
    "29": "return-dark",
    "30": "return-dark-green",

    "53": "right-dark",
    "54": "right-light",
    "55": "right-dark-green",
    "58": "right-light-green",
}


ct = 0

with open('src/global_styl/buttons.styl', 'w') as styl:
    styl.write(HEADER)

    for filename in glob('%s/*.svg' % (SOURCE_DIRECTORY)):
        m = re.match('.*-([0-9]+).svg$', filename)

        if m:
            num = m.group(1)
            if num in stupid_map:
                print('%s %s' % (num, filename))
                name = stupid_map[num]
                shutil.copyfile(filename, '%s/%s.svg' % (DEST_DIRECTORY, name))
                ct += 1

                styl.write('.%s { background-image: svg-load("../assets/buttons/%s.svg"); }\n' % (name, name));

    styl.write(".left-dark { @extend .right-dark; transform: scaleX(-1); }\n")
    styl.write(".left-light { @extend .right-light; transform: scaleX(-1); }\n")
    styl.write(".left-dark-green { @extend .right-dark-green; transform: scaleX(-1); }\n")
    styl.write(".left-light-green { @extend .right-light-green; transform: scaleX(-1); }\n")

    styl.write(".up-dark { @extend .right-dark; transform: rotate(-90deg); }\n")
    styl.write(".up-light { @extend .right-light; transform: rotate(-90deg); }\n")
    styl.write(".up-dark-green { @extend .right-dark-green; transform: rotate(-90deg); }\n")
    styl.write(".up-light-green { @extend .right-light-green; transform: rotate(-90deg); }\n")


    styl.write("""
.stone-button {
    display: inline-flex;
    border: 1px solid transparent;
    border-radius: 5rem;
    min-height: 3.7rem;
    min-width: 3.7rem;
    max-height: 3.7rem;
    max-width: 3.7rem;
    background-size: cover;

    +portrait() {
        min-height: 3.0rem;
        min-width : 3.0rem;
        max-height: 3.0rem;
        max-width : 3.0rem;
    }

    cursor: pointer;
}
""")

    for button in ('check', 'x', 'flag', 'chat', 'return', 'left', 'right', 'up'):
        styl.write("""
button.%(name)s, .stone-button-%(name)s {
    @extend .stone-button;
    @extend .%(name)s-light;
    &:hover {
        @extend .%(name)s-light-green;
    }
    &:active {
        @extend .%(name)s-dark-green;
    }
}
        """ % {"name": button})

